version: 2.1

orbs:
  docker: circleci/docker@1.0.1

defaults: &defaults
  resource_class: 'small'
  docker:
    - image: circleci/python:3.8-buster

jobs:
  lint_and_test:
    <<: *defaults
    steps:

      - checkout

      - restore_cache:
          key: deps-{{ checksum "src/requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r src/requirements.txt

      - save_cache:
          key: deps-{{ checksum "src/requirements.txt" }}
          paths:
            - "venv"

      - run:
          name: Linter
          command: |
            . venv/bin/activate
            cd src && flake8

      - run:
          name: Test
          command: |
            . venv/bin/activate
            cd src && pytest

      - persist_to_workspace:
          root: .
          paths:
            - "venv"
            - "src"
            - ".circleci"

  deploy:
    <<: *defaults

    steps:
      - attach_workspace:
          at: .


workflows:
  main:
    jobs:
      - lint_and_test
      - deploy:
          requires:
            - lint_and_test
          filters:
            branches:
              only: master
