name: build

on:
  push:
    branches:
      - master


jobs:
  test-lint:

    runs-on: ubuntu-latest
    container: python:3.8

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        python3 -m venv venv
        . venv/bin/activate
        pip install --upgrade pip
        pip install -r src/requirements.txt

    - name: Lint
      run: |
        . venv/bin/activate
        cd src
        flake8

    - name: Test
      run: |
        . venv/bin/activate
        cd src
        python -m pytest

  build:

    runs-on: ubuntu-latest
    needs: test-lint

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_SECRET }}

    - name: Build image and push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: ./src
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/checklistbot:${{ github.sha }}, ${{ secrets.DOCKERHUB_USERNAME }}/checklistbot:latest

  deploy:

    runs-on: ubuntu-latest
    needs: build

    steps:

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        key: ${{ secrets.DEPLOY_KEY }}
        script_stop: true
        script: |
          export CIRCLE_SHA1=${{ github.sha }}
          /srv/deploy-and-wait.sh checklistbot
